version: '3.8'

services:
  app:
    image: blob-storage-manager-img
    container_name: blob-storage-manager
    build: .
    ports:
      - "7999:7999"
    env_file:
      - .env
    restart: always
    volumes:
      - ./downloads:/usr/src/app/downloads
    networks:
      - vgw-network

networks:
  vgw-network:
    name: vgw-network
    driver: bridge
